fix logging on exception
On exception the type str was inserted on log causing the following crash.
  File "/usr/lib/enigma2/python/Plugins/Extensions/SDGRadio/plugin.py", line 737, in showLog
    text = "".join(self.log)
TypeError: sequence item 39: expected string, type found