Add missing self.dabgain
Fixes issue:
File "/usr/lib/enigma2/python/Plugins/Extensions/SDGRadio/plugin.py", line 460, in getDabGain
AttributeError: 'SDGRadioScreen' object has no attribute 'dabgain'

Issue introduce due to partial merge of #13.